name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          IMAGE_TAG=1692524249
          IMAGE_NAME=crazythought
          DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
          docker build . --file Dockerfile --tag $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG

      - name: Push Docker Image
        run: |
          IMAGE_TAG=1692524249
          IMAGE_NAME=crazythought
          DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
          docker push $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG

  run_compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Start Docker Compose services
        run: docker-compose up -d
