name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          IMAGE_TAG=$(date +%s)
          docker build . --file Dockerfile --tag crazythought:$IMAGE_TAG

      - name: Push Docker Image
        run: |
          IMAGE_TAG=$(date +%s)
          docker tag crazythought:$IMAGE_TAG ${{ secrets.DOCKER_USERNAME }}/crazythought:$IMAGE_TAG
          docker push ${{ secrets.DOCKER_USERNAME }}/crazythought:$IMAGE_TAG

